// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Bahnfrei contributors

// Package pdf generates printable documents — capture sheets, start and
// result lists (SYS-072). It is deliberately generic: callers assemble a
// [Document] (a shared [Header] plus one or more [Section] tables of
// already-translated, already-formatted strings) and [Build] renders it;
// no bahnfrei domain type crosses this package boundary, so it stays
// trivially unit-testable and reusable for whatever printable comes next
// (start lists, the record checklist, SYS-051).
//
// Library choice (TASK-011, PoC scope): codeberg.org/go-pdf/fpdf — a pure
// Go, MIT-licensed, actively maintained fork of the archived
// github.com/jung-kurt/gofpdf. Selection rationale recorded in
// docs/architecture/architecture.md §8. Output structure is verified in
// tests via github.com/ledongthuc/pdf (BSD-3-Clause, a maintained fork of
// rsc.io/pdf), which parses the generated bytes back into plain text —
// both licences are compatible with AGPL-3.0-only distribution (ADR-001).
package pdf
