// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Bahnfrei contributors

package exchange

import (
	"bufio"
	"bytes"
	"encoding/csv"
	"fmt"
	"strconv"
	"strings"
)

// FinishLynx data-file field layouts encoded here are transcribed from the
// vendor's own documentation (ADR-006 §2 "format conformance is
// fixture-driven"):
//
//   - lynx.ppl / lynx.evt / lynx.sch formats and the allowable CR-status
//     vocabulary: FinishLynx Help — "Database Files"
//     (https://help.finishlynx.com/Content/OnlineManual/DatabaseFiles.htm,
//     fetched 2026-07-13).
//   - .lif competitor-row field order (Place, ID, lane, last name, first
//     name, affiliation, <time>, license, <delta time>, <ReacTime>,
//     <splits>, time trial start time, user 1-3): FinishLynx — "File
//     Formats for Meet Management Integration"
//     (https://finishlynx.com/file-formats-meet-manager/, cited already in
//     docs/research/domain-athletics.md D7.2 and
//     docs/research/competitive-analysis.md C5).
//   - Full 19-field competitor row (adding delta time 2/3, speed, pace) and
//     a real multi-competitor .lif sample (status codes, blank/unassigned
//     lanes, DNS rows): meettrax docs — "Lynx lif file"
//     (https://help.meettrax.com/files/lynx/lif, fetched 2026-07-13),
//     itself citing the FinishLynx page above and stating "the file is
//     identical to the evt with the only difference being that the place
//     has been populated" — the basis for sharing CompetitorRow between
//     EncodeEVT and EncodeLIF here.
//
// FinishLynx is Windows software; every file it reads/writes uses CRLF line
// endings, so Encode* below writes "\r\n". Parse* accepts either (Go's
// bufio.Scanner strips a trailing "\r" from each line automatically).

const crlf = "\r\n"

// Person is one lynx.ppl entry: an ID-to-identity lookup row (Database
// Files, "Creating the People List").
type Person struct {
	ID          string // "0" means no ID number (spec: never blank)
	LastName    string
	FirstName   string
	Affiliation string
	License     string
}

// EncodePPL renders people as a lynx.ppl file: "ID number, last name, first
// name, affiliation, license, user 1, user 2, user 3" (trailing user
// fields are always empty — this system has no per-competitor user-field
// data to place there).
func EncodePPL(people []Person) []byte {
	var buf bytes.Buffer
	buf.WriteString("; lynx.ppl generated by bahnfrei (SYS-060, ADR-006) — do not hand-edit, re-export instead" + crlf)
	for _, p := range people {
		writeCSVLine(&buf, []string{idOrZero(p.ID), p.LastName, p.FirstName, p.Affiliation, p.License, "", "", ""})
	}
	return buf.Bytes()
}

// ParsePPL reads a lynx.ppl file back into Person rows (round-trip
// self-check; SYS-062-style fixture verification). Comment lines
// (leading ';') and blank lines are skipped.
func ParsePPL(data []byte) ([]Person, error) {
	var out []Person
	err := scanLines(data, func(line string) error {
		fields, err := splitCSVLine(line)
		if err != nil {
			return fmt.Errorf("ppl line %q: %w", line, err)
		}
		for len(fields) < 5 {
			fields = append(fields, "")
		}
		out = append(out, Person{
			ID: fields[0], LastName: fields[1], FirstName: fields[2],
			Affiliation: fields[3], License: fields[4],
		})
		return nil
	})
	return out, err
}

// CompetitorRow is one participant line: inside a lynx.evt event block
// before the race (Place is unused there), or one result line inside a
// .lif file after it (Place populated — "the file is identical to the evt
// with the only difference being that the place has been populated",
// meettrax docs). Place holds either a 1-based finishing place ("1", "2",
// …), a CR-status code ("DNS", "DQ", …), or "" for a lane with no result
// yet.
type CompetitorRow struct {
	Place          string
	ID             string
	Lane           int
	LastName       string
	FirstName      string
	Affiliation    string
	Time           string
	License        string
	DeltaTime      string
	ReacTime       string
	Splits         string
	TimeTrialStart string
	User1          string
	User2          string
	User3          string
	DeltaTime2     string
	DeltaTime3     string
	Speed          string
	Pace           string
}

func (c CompetitorRow) fields() []string {
	lane := ""
	if c.Lane != 0 {
		lane = strconv.Itoa(c.Lane)
	}
	return []string{
		c.ID, lane, c.LastName, c.FirstName, c.Affiliation, c.Time, c.License,
		c.DeltaTime, c.ReacTime, c.Splits, c.TimeTrialStart,
		c.User1, c.User2, c.User3, c.DeltaTime2, c.DeltaTime3, c.Speed, c.Pace,
	}
}

func competitorFromFields(fields []string) CompetitorRow {
	for len(fields) < 18 {
		fields = append(fields, "")
	}
	lane, _ := strconv.Atoi(strings.TrimSpace(fields[1]))
	return CompetitorRow{
		ID: fields[0], Lane: lane, LastName: fields[2], FirstName: fields[3],
		Affiliation: fields[4], Time: fields[5], License: fields[6],
		DeltaTime: fields[7], ReacTime: fields[8], Splits: fields[9],
		TimeTrialStart: fields[10], User1: fields[11], User2: fields[12], User3: fields[13],
		DeltaTime2: fields[14], DeltaTime3: fields[15], Speed: fields[16], Pace: fields[17],
	}
}

// Event is one event/round/heat block: the lynx.evt header fields
// ("Creating the Start List") plus its competitor lines. A .lif file is
// exactly one Event with Competitors[i].Place populated.
type Event struct {
	Number          int
	Round           int
	Heat            int
	Name            string
	Wind            string
	WindUnit        string
	Template        string
	CaptureTime     string
	CaptureDuration string
	Distance        string
	StartTime       string
	WindMode        string
	LapInfo         string
	Competitors     []CompetitorRow
}

func (e Event) headerFields() []string {
	return []string{
		strconv.Itoa(e.Number), strconv.Itoa(e.Round), strconv.Itoa(e.Heat), e.Name,
		e.Wind, e.WindUnit, e.Template, e.CaptureTime, e.CaptureDuration,
		e.Distance, e.StartTime, e.WindMode, e.LapInfo,
	}
}

// evtCompetitorIndent is the delimiter EncodeEVT prepends to every
// competitor line (Database Files: a participant line is introduced by
// "<tab, space, or comma>"). A literal tab is used — unlike a leading
// comma, it does not itself consume a CSV field position, so the line's
// first CSV field is unambiguously the ID field on both write and read.
const evtCompetitorIndent = "\t"

// EncodeEVT renders events as a lynx.evt start-list file: one header line
// per event/round/heat followed by its competitor lines (no Place field —
// the race has not run yet).
func EncodeEVT(events []Event) []byte {
	var buf bytes.Buffer
	buf.WriteString("; lynx.evt generated by bahnfrei (SYS-060, ADR-006) — do not hand-edit, re-export instead" + crlf)
	for _, e := range events {
		writeCSVLine(&buf, e.headerFields())
		for _, c := range e.Competitors {
			buf.WriteString(evtCompetitorIndent)
			writeCSVLine(&buf, c.fields())
		}
	}
	return buf.Bytes()
}

// ParseEVT reads a lynx.evt file back into Events. A line is an event
// header when it carries no leading indent/backslash and its first field
// parses as an integer; a tab/space-indented or backslash-prefixed line is
// a competitor line of the most recently seen event (Database Files: "To
// indicate a competitor status, the first character of the participant
// line must be a backslash").
func ParseEVT(data []byte) ([]Event, error) {
	var out []Event
	err := scanLines(data, func(line string) error {
		status, body, statusPrefixed := cutStatusPrefix(line)
		indented := false
		if !statusPrefixed && (strings.HasPrefix(body, "\t") || strings.HasPrefix(body, " ") || strings.HasPrefix(body, ",")) {
			indented = true
			body = strings.TrimPrefix(strings.TrimPrefix(body, "\t"), " ")
			body = strings.TrimPrefix(body, ",") // a comma-indented line still needs its phantom field dropped
		}
		fields, err := splitCSVLine(body)
		if err != nil {
			return fmt.Errorf("evt line %q: %w", line, err)
		}
		if !statusPrefixed && !indented && isEventHeader(fields) {
			num, _ := strconv.Atoi(fields[0])
			round, heat := 1, 1
			if len(fields) > 1 {
				round, _ = strconv.Atoi(fields[1])
			}
			if len(fields) > 2 {
				heat, _ = strconv.Atoi(fields[2])
			}
			name := ""
			if len(fields) > 3 {
				name = fields[3]
			}
			e := Event{Number: num, Round: round, Heat: heat, Name: name}
			for i, v := range []*string{&e.Wind, &e.WindUnit, &e.Template, &e.CaptureTime, &e.CaptureDuration, &e.Distance, &e.StartTime, &e.WindMode, &e.LapInfo} {
				if idx := i + 4; idx < len(fields) {
					*v = fields[idx]
				}
			}
			out = append(out, e)
			return nil
		}
		if len(out) == 0 {
			return fmt.Errorf("evt: competitor line %q precedes any event header", line)
		}
		c := competitorFromFields(fields)
		if statusPrefixed {
			c.Place = status
		}
		last := &out[len(out)-1]
		last.Competitors = append(last.Competitors, c)
		return nil
	})
	return out, err
}

// isEventHeader reports whether fields looks like an event header line
// (first field is a bare non-negative integer) rather than a competitor
// line's leading ID (which the spec allows to be prefixed by a delimiter,
// see ParseEVT/cutStatusPrefix — plain unprefixed competitor lines whose ID
// happens to parse as an integer are the one genuine ambiguity the format
// leaves the *producer* to avoid, per Database Files' backslash-prefix
// escape hatch).
func isEventHeader(fields []string) bool {
	if len(fields) == 0 {
		return false
	}
	_, err := strconv.Atoi(strings.TrimSpace(fields[0]))
	return err == nil && len(fields) >= 4
}

// cutStatusPrefix strips a leading backslash (Database Files: competitor
// status-line marker) and returns the status token that follows up to the
// first comma, alongside the remainder of the line.
func cutStatusPrefix(line string) (status, rest string, ok bool) {
	if !strings.HasPrefix(line, `\`) {
		return "", line, false
	}
	body := line[1:]
	if i := strings.IndexByte(body, ','); i >= 0 {
		return body[:i], body[i+1:], true
	}
	return body, "", true
}

// ScheduleEntry is one lynx.sch line: the order events run in
// ("Creating the Schedule File"). Comment is written as a preceding
// ';'-prefixed line (the sample file's own convention) purely for the
// human operator reading the file; it carries no machine meaning.
type ScheduleEntry struct {
	EventNumber int
	Round       int
	Heat        int
	Comment     string
}

// EncodeSCH renders entries as a lynx.sch schedule file.
func EncodeSCH(entries []ScheduleEntry) []byte {
	var buf bytes.Buffer
	buf.WriteString("; lynx.sch generated by bahnfrei (SYS-060, ADR-006) — do not hand-edit, re-export instead" + crlf)
	for _, e := range entries {
		if e.Comment != "" {
			buf.WriteString(";" + e.Comment + crlf)
		}
		writeCSVLine(&buf, []string{strconv.Itoa(e.EventNumber), strconv.Itoa(e.Round), strconv.Itoa(e.Heat)})
	}
	return buf.Bytes()
}

// ParseSCH reads a lynx.sch file back into ScheduleEntry rows. A
// ';'-prefixed line is folded into Comment on the next data line rather
// than dropped, so EncodeSCH/ParseSCH round-trip losslessly.
func ParseSCH(data []byte) ([]ScheduleEntry, error) {
	var out []ScheduleEntry
	var pendingComment string
	err := scanLinesKeepComments(data, func(line string, isComment bool) error {
		if isComment {
			pendingComment = strings.TrimPrefix(line, ";")
			return nil
		}
		fields, err := splitCSVLine(line)
		if err != nil {
			return fmt.Errorf("sch line %q: %w", line, err)
		}
		for len(fields) < 3 {
			fields = append(fields, "1")
		}
		num, _ := strconv.Atoi(fields[0])
		round, _ := strconv.Atoi(fields[1])
		heat, _ := strconv.Atoi(fields[2])
		out = append(out, ScheduleEntry{EventNumber: num, Round: round, Heat: heat, Comment: pendingComment})
		pendingComment = ""
		return nil
	})
	return out, err
}

// EncodeLIF renders one event's result file: the header line, then one
// competitor line per lane with Place populated (a finishing place, a CR
// status code, or blank for a lane with no result — see the meettrax
// sample transcribed in finishlynx_test.go).
func EncodeLIF(e Event) []byte {
	var buf bytes.Buffer
	writeCSVLine(&buf, e.headerFields())
	for _, c := range e.Competitors {
		fields := append([]string{c.Place}, c.fields()...)
		writeCSVLine(&buf, fields)
	}
	return buf.Bytes()
}

// ParseLIF reads a .lif result file: a single header line (event/round/heat
// identity, wind, start time) followed by one competitor/result line per
// lane. Comment and blank lines are skipped; ParseLIF returns an error if
// no header line is found.
func ParseLIF(data []byte) (Event, error) {
	var e Event
	haveHeader := false
	err := scanLines(data, func(line string) error {
		fields, err := splitCSVLine(line)
		if err != nil {
			return fmt.Errorf("lif line %q: %w", line, err)
		}
		if !haveHeader {
			for len(fields) < 13 {
				fields = append(fields, "")
			}
			num, _ := strconv.Atoi(strings.TrimSpace(fields[0]))
			round, _ := strconv.Atoi(strings.TrimSpace(fields[1]))
			heat, _ := strconv.Atoi(strings.TrimSpace(fields[2]))
			e = Event{
				Number: num, Round: round, Heat: heat, Name: fields[3],
				Wind: fields[4], WindUnit: fields[5], Template: fields[6],
				CaptureTime: fields[7], CaptureDuration: fields[8], Distance: fields[9],
				StartTime: fields[10], WindMode: fields[11], LapInfo: fields[12],
			}
			haveHeader = true
			return nil
		}
		for len(fields) < 19 {
			fields = append(fields, "")
		}
		place := fields[0]
		c := competitorFromFields(fields[1:])
		c.Place = place
		e.Competitors = append(e.Competitors, c)
		return nil
	})
	if err != nil {
		return Event{}, err
	}
	if !haveHeader {
		return Event{}, fmt.Errorf("lif: no event header line found")
	}
	return e, nil
}

// idOrZero implements Database Files' "To indicate no ID number you must
// put a zero in the ID field" rule.
func idOrZero(id string) string {
	if id == "" {
		return "0"
	}
	return id
}

// writeCSVLine appends one CRLF-terminated, comma-separated line to buf,
// quoting any field that needs it (embedded comma/quote — Database Files:
// "If any of the fields contain a comma … the data … should be placed in
// quotes"). encoding/csv already applies exactly that quoting rule.
func writeCSVLine(buf *bytes.Buffer, fields []string) {
	w := csv.NewWriter(buf)
	w.UseCRLF = true
	_ = w.Write(fields)
	w.Flush()
}

// splitCSVLine parses one already-isolated line as a single CSV record,
// tolerating a ragged/short field count (FinishLynx: "you can omit
// unnecessary or unknown information").
func splitCSVLine(line string) ([]string, error) {
	r := csv.NewReader(strings.NewReader(line))
	r.FieldsPerRecord = -1
	rec, err := r.Read()
	if err != nil {
		return nil, err
	}
	return rec, nil
}

// scanLines calls fn for every non-blank, non-comment line of data
// (Database Files: "Any line starting with a semicolon is ignored").
func scanLines(data []byte, fn func(line string) error) error {
	return scanLinesKeepComments(data, func(line string, isComment bool) error {
		if isComment {
			return nil
		}
		return fn(line)
	})
}

// scanLinesKeepComments is scanLines' generalisation for ParseSCH, which
// needs a comment line's text folded into the following data row.
func scanLinesKeepComments(data []byte, fn func(line string, isComment bool) error) error {
	sc := bufio.NewScanner(bytes.NewReader(data))
	sc.Buffer(make([]byte, 0, 4096), 1<<20)
	for sc.Scan() {
		line := strings.TrimRight(sc.Text(), "\r")
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, ";") {
			if err := fn(trimmed, true); err != nil {
				return err
			}
			continue
		}
		if err := fn(line, false); err != nil {
			return err
		}
	}
	return sc.Err()
}
